# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-09 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190409_0839'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.IntegerField(choices=[(0, 'Patient'), (1, 'Doctor'), (2, 'Nurse')]),
        ),
    ]
