# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-11 13:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190411_1218'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visit',
            unique_together=set([('start_date', 'doctor'), ('end_date', 'doctor')]),
        ),
    ]
